### ISSUE TITLE
Barely works

### ISSUE THREAD

**Issue by martinszy** [eleyine/wikicode-renderer#1]
This code is not very useful, it extracts the text from my HTML and marks the titles in wiki format, nothing else.
All the work of exporting the zip file and unpacking it to obtain the html and then running the app I had to clone from github to only obtain a barely useful function make this a small waste of my time that I will document here for the next sorry soul that finds it.

If you happen to know of a code that works better, please let me know.

I also tried to use the wikinotes fork, but the python code was broken. I had to change the name of a module to get it to run, and then hardcode the filenames, and then it threw an error on me:

``` python
Traceback (most recent call last):
  File "wikicodify.py", line 199, in <module>
    wikicodify(input_file, output_file, wikidict)
  File "wikicodify.py", line 168, in wikicodify
    format = get_format(element, wikidict, match.group())
  File "wikicodify.py", line 48, in get_format
    for class_name in tag_classes:
```

**Comment by dellsystem** [comment]
Hi @martinszy,

The code in this repo was written approximately 4 years ago for the author's personal use, and hasn't been touched since then. Seems like Google Docs has changed significantly in the meantime, which is unfortunate. I'm sorry to hear that you felt like your time was wasted, but I don't think it was intended for public consumption.

What do you mean by "I also tried to use the wikinotes fork"?

**Comment by martinszy** [comment]
Thanks Wendy, yes, I agree that it was not intended for public consumption,
yet it is public so I wanted to document my experience. Mayb it sounded
harsh, but I had no intention to offend the author.

The wikinotes work is a work by the user wikinotes, here:
https://github.com/wikinotes/google-docs-to-wikicode

Martín.

2015-01-31 23:28 GMT+00:00 Wendy Liu notifications@github.com:

> Hi @martinszy https://github.com/martinszy,
> 
> The code in this repo was written approximately 4 years ago for the
> author's personal use, and hasn't been touched since then. Seems like
> Google Docs has changed significantly in the meantime, which is
> unfortunate. I'm sorry to hear that you felt like your time was wasted, but
> I don't think it was intended for public consumption.
> 
> What do you mean by "I also tried to use the wikinotes fork"?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eleyine/wikicode-renderer/issues/1#issuecomment-72342439
> .

## 

_Martín Szyszlican_
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by dellsystem** [comment]
Ah, I see what you mean. Maybe @eleyine can weigh in, but since neither repository has been updated since 2011, I would recommend looking for another solution. Good luck!

**Comment by eleyine** [comment]
Hello @martinszy,

I'm sorry my code was a source of frustration. As @dellsystem pointed out, it was intended for internal use at @wikinotes when it still was a MediaWiki. If you [had inspected the (very short) code](https://github.com/eleyine/wikicode-renderer/blob/master/wikicode.py#L32), you would have seen that all it does is change headers. I guess I intended to add functionality to it but our team moved away from MediaWiki and on to a customised Django app engineered by @dellsystem. In any case, if you are looking for alternatives, I recommend [pandoc](http://johnmacfarlane.net/pandoc/README.html).

You can try the command `pandoc -f docx -t mediawiki -o output_file.wiki input_file.docx`. I'm not sure if it works well for wikiformat but it's excellent for markdown ( `pandoc -f docx -t markdown -o output_file.md input_file.docx`). Since wiki markup isn't that far from markdown, you may use the pandoc conversion as an intermediate step.

Hope this helps.
